version: '3'
services:
  mongodb:
    image: mongo:v1.0.0
    restart: on-failure
    ports:
      - "27017:27017"
    dns: 8.8.8.8
    ulimits:
      nproc: 65535
      nofile:
        soft: 40000
        hard: 40000
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /var/lib/mongo/data/db:/data/db
      - /var/lib/mongo/mongod.conf:/etc/mongod.conf
    command: mongod --config /etc/mongod.conf